site_name: How to Crack Jetbrains Suites ?
theme:
  name: material
  language: my
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/HanZawNyein/how-to-crack-jetbrains-suite
repo_name: HanZawNyein/how-to-crack-jetbrains-suite
